remote_theme: jasongrimes/jekyll-chapterbook

title: Fretboard Foundation
longtitle: Fretboard Foundation
author: Jason Grimes
email: jason@grimesit.com
description: >
  Practical building-blocks for intermediate guitarists.

copyright:
  start_year: 2022
  link_slug: copyright

# Customize the link favicon in header. Will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     /assets/gitbook/images/favicon.ico

# Markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true
syntax_highlighter_style: colorful
markdown_ext:     markdown,mkdown,mkdn,mkd,md

exclude:
  - _drafts

page_width: 800px

destination:      ./_site
incremental:      false
regenerate:       true  

bottom_nav:
- label: Home
  url: /
- label: Contents
  url: /toc
- label: About
  url: /about
- label: Privacy
  url: /privacy

sidebar_nav_top:
- label: About this site
  url: /about
- label: Draft outline
  url: /outline

sidebar_nav_bottom:
- label: Privacy statement
  url: /privacy

github_edit:
  enabled: true
  base_url: https://github.com/jasongrimes/fretboardfoundation/edit/main/

extra_css:
    - assets/fretboardfoundation.css

collections:
  chapters:
    output: true
  pages:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "chapters"
    values:
      layout: "chapter"
      permalink: /:slug:output_ext
