remote_theme: jasongrimes/jekyll-gitbook

title: Fretboard Foundation
longtitle: Fretboard Foundation
author: Jason Grimes
email: jason@grimesit.com
#description: >
#  For intermediate guitarists building toward mastery.

toc:
  enabled: true
  h_min: 1
  h_max: 3

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path: assets/gitbook/images/favicon.ico

#page_width: 800px

destination:      ./_site
incremental:      false
regenerate:       true


# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:     markdown,mkdown,mkdn,mkd,md

# Permalinks
##permalink:        /:categories/:year-:month-:day-:title:output_ext
#permalink: /:slug:output_ext

exclude:
  - _drafts
  - .idea

#
# Chapterbook config
#

# Chapters can be hidden from navigation in production environments by adding ".draft" to the index at the start of their filename.
# (For example, rename 010-introduction.md to 010.draft-introduction.md)
# By default, these draft chapters are still visible in non-production environments.
# Hide them in all environments by setting always_hide_draft_chapters to true.
always_hide_draft_chapters: true

copyright:
  start_year: 2022
  link_slug: copyright

github_edit:
  enabled: true
  base_url: https://github.com/jasongrimes/ff-next/edit/main/

extra_css:
    - css/chapterbook.css
    - css/fretboardfoundation.css

collections:
  chapters:
    output: true
  pages:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "chapters"
    values:
      layout: "chapter"
      permalink: /:slug:output_ext
