remote_theme: jasongrimes/jekyll-chapterbook

title: Fretboard Foundation
longtitle: Fretboard Foundation
author: Jason Grimes
email: jason@grimesit.com
description: >
  Practical building-blocks for intermediate guitarists.

# A copyright notice will be shown at the bottom of each page,
# with the current year and the author name.
# Set a link_slug to link to a copyright page.
# Set a start_year to have the copyright render as "start_year - current_year" (if the years are different)
# Set copyright: false to disable.
copyright:
  start_year: 2022
  link_slug: copyright

# Customize the link favicon in header. Will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path: /assets/gitbook/images/favicon.ico

#
# Navigation menus
#

# Links shown above the TOC in the sidebar
sidebar_nav_top:
- label: About this site
  url: /about
- label: Draft outline
  url: /outline

# Links shown below the TOC in the sidebar
sidebar_nav_bottom:
- label: Privacy statement
  url: /privacy

# Navigation shown at the bottom of the page
bottom_nav:
- label: Home
  url: /
- label: Contents
  url: /toc
- label: About
  url: /about
- label: Privacy
  url: /privacy

# Whether to show chapter headings as a table of contents at the top of each chapter page.
# Override in page front matter with disable_toc: true
in_chapter_toc:
  enabled: true
  h_min: 2
  h_max: 3

# Whether to show chapter heading sub-navigation beneath the active chapter in the sidebar.
# Override in page front matter with disable_toc: true
sidebar_toc:
  enabled: false
  h_min: 2
  h_max: 3

# 
# End navigation menus
#

# Show a link to edit each page on GitHub
github_edit:
  enabled: true
  base_url: https://github.com/jasongrimes/fretboardfoundation/edit/main/

# Custom CSS
extra_css:
    - assets/fretboardfoundation.css

# Chapters can be hidden from navigation by adding ".draft" to the index at the start of their filename.
# (For example, rename 010-introduction.md to 010.draft-introduction.md)
#
# To make the drafts appear in the navigation in development environments,
# set show_drafts_in_dev to true.
show_drafts_in_dev: false





exclude:
  - _drafts

page_width: 800px

destination: ./_site
incremental: false
regenerate: true

plugins:
#  - jekyll-feed
  - jekyll-readme-index
#  - jemoji

collections:
  chapters:
    output: true
  pages:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "chapters"
    values:
      layout: "chapter"
      permalink: /:slug:output_ext

# Markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true
syntax_highlighter_style: colorful
markdown_ext:     markdown,mkdown,mkdn,mkd,md
