remote_theme: jasongrimes/jekyll-gitbook

title: Fretboard Foundation
longtitle: Fretboard Foundation
author: Jason Grimes
email: jason@grimesit.com
#description: >
#  For intermediate guitarists building toward mastery.

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path: assets/gitbook/images/favicon.ico

#page_width: 800px

destination:      ./_site
incremental:      false
regenerate:       true


# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:     markdown,mkdown,mkdn,mkd,md

# Permalinks
##permalink:        /:categories/:year-:month-:day-:title:output_ext
#permalink: /:slug:output_ext

exclude:
  - _drafts
  - .idea

#
# Gitbookish config
#

# Chapters can be hidden from navigation by adding ".draft" to the index at the start of their filename.
# (For example, rename 010-introduction.md to 010.draft-introduction.md)
#
# To make the drafts appear in the navigation in development environments,
# set show_drafts_in_dev to true.
show_drafts_in_dev: false

# Override in page front matter with disable_toc: true
sidebar_toc:
  enabled: true
  h_min: 2
  h_max: 3

# Override in page front matter with disable_toc: true
in_chapter_toc:
  enabled: true
  h_min: 2
  h_max: 3

copyright:
  start_year: 2022
  link_slug: copyright

bottom_nav:
- label: Home
  url: /
- label: Contents
  url: /toc
- label: About
  url: /about
- label: Privacy
  url: /privacy

sidebar_nav_top:
- label: About this site
  url: /about
- label: Draft outline
  url: /outline

sidebar_nav_bottom:
- label: Privacy statement
  url: /privacy

github_edit:
  enabled: true
  base_url: https://github.com/jasongrimes/ff-next/edit/main/

extra_css:
    - assets/fretboardfoundation.css

collections:
  chapters:
    output: true
  pages:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "chapters"
    values:
      layout: "chapter"
      permalink: /:slug:output_ext
