remote_theme: jasongrimes/jekyll-gitbook

title: Fretboard Foundation
longtitle: Fretboard Foundation
author: Jason Grimes
email: jason@grimesit.com
description: >
  For intermediate guitarists building toward mastery.

toc:
  enabled: true
  h_min: 1
  h_max: 3

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path: /assets/gitbook/images/favicon.ico

#page_width: 800px

destination:      ./_site
incremental:      false
regenerate:       true


# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:     markdown,mkdown,mkdn,mkd,md

# Permalinks
##permalink:        /:categories/:year-:month-:day-:title:output_ext
##permalink: /:slug:output_ext

exclude:
  - _drafts

collections:
  chapters:
    output: true

github_edit:
  enabled: true
  base_url: https://github.com/jasongrimes/ff-next/edit/main/


defaults:
  -
    scope:
      path: ""
      type: "chapters"
    values:
      layout: "chapter"
      permalink: /:slug:output_ext
  -
    scope:
      path: ""
      type: "front"
    values:
      layout: "chapter"
      permalink: /:slug:output_ext
  -
    scope:
      path: ""
      type: "back"
    values:
      layout: "chapter"
      permalink: /:slug:output_ext

